name: follow
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

 
  google_fonts: ^8.2.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0


flutter:
  fonts:
      - family: CookieFont
        fonts:
          - asset: assets/fonts/Cookie-Regular.ttf

  uses-material-design: true
  assets:
    - assets/data/babel_hexagon.txt
    - assets/data/babelia_first_record.txt
    - assets/data/babelia_record_01.txt
    - assets/data/babelia_record_02.txt
    - assets/data/babelia_record_03.txt
    - assets/data/babelia_record_04.txt
    - assets/data/babelia_record_05.txt
    - assets/data/babelia_record_06.txt
 